<form action="/userdashboard/adddata" method="post">
    id:
    <input type="text" name="id" placeholder="enter id" class="form-control">
    <br>
    title:
    <input type="text" name="title" placeholder="enter title" class="form-control">
    <br>
    Author:
    <input type="text" name='author' placeholder='enter author' class="form-control">
    <br>
    Pages:
    <input type="text" name='pages' placeholder='Enter NO of Pages' class="form-control">
    <br>
    <input type="submit" class='btn btn-submit'>

</form>
