<table class="table table-hovered table-striped table-bordered">
    <caption>table shows orders detail</caption>
    <thead>
        <th>id</th>
        <th>title </th>
        <th> Author </th>
        <th>Pages</th>

    </thead>
    <tbody>
        <?php
        foreach ($book as $key => $value) {
           foreach ($value as $key1 => $value1) {
            echo "<tr><td>$value1->id</td><td>$value1->title</td><td>$value1->author</td><td>$value1->pages</td></tr>";
           }
        }
        ?>
    </tbody>
</table>
<table class="table table-hovered table-striped table-bordered">
    <caption>table shows users detail</caption>
    <thead>
        <th>Customer Name</th>
        <th>Customer email</th>
        <th>Customer PinCode </th>
        <th>Role</th>
    </thead>
    <tbody>
        <?php
        foreach ($user as $key => $value) {
           echo "<tr><td>$value->name</td><td>$value->email</td><td>$value->pincode</td><td>$value->role</td></tr>";
        }
        ?>
    </tbody>
</table>
<table class="table table-hovered table-striped table-bordered">
    <caption>table shows order details</caption>
    <thead>
        <th>user_id</th>
        <th>book_id</th>
    </thead>
    <tbody>
        <?php
        foreach ($order as $key => $value) {
            echo "<tr><td>$value->user_id</td><td>$value->book_id</td></tr>";
        }
        ?>
    </tbody>
</table>
