<h2>Add Resturant Details</h2>
<form action="adddetail">
    name : <input type="text" placeholder="Enter name" class="form-control" name='name'>
    <br>
    restaurant id : <input type="number" placeholder="enter id"class='form-control' name='id'>
    <br>
    cuisine : <input type="text" placeholder="Enter cuisine" class="form-control" name='cuisine'>
    <br>
    borough :  <input type="text" placeholder="Enter borough" class="form-control" name='borough'>
    <br>
    address:
    <br>
    building : <input type="number" placeholder="enter building number"class='form-control' name='building'>
    street : <input type="text" placeholder="enter street"class='form-control' name='street'>
    zip-code : <input type="number" placeholder="enter zip number"class='form-control' name='zip'>
    <input type="submit" value="Submit" class='btn btn-primary p-1 mt-2'>
</form>
