<a href='manager/add' class='btn btn-success'>Add Resturant</a>
<table class="table table-hovered table-striped table-bordered">
    <caption>table shows orders detail</caption>
    <thead>
        <th>Customer Name</th>
        <th>Customer Address</th>
        <th>Resturant Name </th>
        <th>Cuisine</th>
        <th>time</th>
    </thead>
    <tbody>
        <?php
        echo $data;
        ?>
    </tbody>
</table>
