<h1 class="text-center p-3 m-2">Review</h1>
<form action="savereview">
Select Grade
    <select name="grade" class='form-control'>
        <option>A</option>
        <option>B</option>
        <option>C</option>
        <option>D</option>
        <option>E</option>
    </select>
    Select Score
    <select name="rating" class="form-control">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
    </select>
    <input type="submit" value="Submit" class='btn btn-info p-1 mt-2'>
</form>
